student_and_information/student/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from student import views
from rest_framework.routers import SimpleRouter
router = SimpleRouter()  # 定义一个路由
router.register(r'student',views.StudentEdit) # studentEdit -- 类名

urlpatterns = [
    url(r'^addstu/',views.addStu,name='add'),
    url(r'^index/',login_required(views.index),name='index'),# 返回所有学生信息(必须要登录才能访问)
    url(r'^stupage/',views.stuPage),
    url(r'^addstuinfo/(?P<stu_id>\d+)',views.addStuInfo,name="addinfo"),
    url(r'^showstu/',views.showStu)
]

urlpatterns += router.urls  # 将路径与对应的方法添加到urlpatterns中

student_and_information/student_and_information/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^stuapp/',include('student.urls',namespace='stu')),
    url(r'^uauth/',include('uauth.urls'))
]
from student_and_information import settings
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

student_and_information/uauth/urls.py
from django.conf.urls import url
from uauth import views

urlpatterns = [
    url(r'^regist/',views.regist),
    url(r'^login/',views.login),
    url(r'^logout/',views.logout),
    url(r'^requestcount/',views.requestCount),
    url(r'^djlogin/',views.djLogin),
    url(r'^djregist/',views.djRegist),
    url(r'^djlogout/',views.djLogout),
]

student_and_information/templates/addstu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加学生页面</title>
</head>
<body>
    <form action="{% url 'stu:add' %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td>姓名</td>
                <td>电话</td>
            </tr>
            <tr>
                <td><input type="text" name="name"></td>
                <td><input type="text" name="tel"></td>
            </tr>
            <tr>
                <td><input type="submit" value="提交"></td>
            </tr>
        </table>

    </form>
</body>
</html>

student_and_information/templates/addstuinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加拓展信息</title>
</head>
<body>
 <form action="" method="post" enctype="multipart/form-data">
     {% csrf_token %}
        <table>
            <tr>
                <td><input type="hidden" value="{{ stu_id }}" name="stu_id"></td>
                <td>地址</td>
                <td><input type="text" name="addr"></td>
                <td>头像</td>
                <td><input type="file" name="img"></td>
            </tr>
            <tr>
                <td><input type="submit" value="提交"></td>
            </tr>
        </table>
    </form>
</body>
</html>

student_and_information/templates/day6_login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="pragma" content="no-cache">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="expires" content="0"> 
	<title>登录界面</title>
    <link href="/static/css/default.css" rel="stylesheet" type="text/css" />
	<!--必要样式-->
    <link href="/static/css/styles.css" rel="stylesheet" type="text/css" />
    <link href="/static/css/demo.css" rel="stylesheet" type="text/css" />
    <link href="/static/css/loaders.css" rel="stylesheet" type="text/css" />

	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>

	<script type="text/javascript">
		function login(){
			err_name = $('#err_name').val()
			err_password = $('#err_password').val()
			if(err_name){
				alert(err_name)
			}else if(err_password){
				alert(err_password)
			}
		}
	</script>

</head>
<body onload="login()">
	<div class='login'>
	  <div class='login_title'>
	    <span>管理员登录</span>
	  </div>
		<input type="hidden" id="err_name" value="{{name}}"/>
		<input type="hidden" id="err_password" value="{{password}}"/>
		<form action="" method="post">
            {% csrf_token %}
	  <div class='login_fields'>
	    <div class='login_fields__user'>
	      <div class='icon'>
	        <img alt="" src='/static/img/user_icon_copy.png'>
	      </div>
	      <input name="name" placeholder='用户名' maxlength="16" type='text' autocomplete="off" value=""/>
	        <div class='validation'>
	          <img alt="" src='/static/img/tick.png'>
	        </div>
	    </div>
	    <div class='login_fields__password'>
	      <div class='icon'>
	        <img alt="" src='/static/img/lock_icon_copy.png'>
	      </div>
	      <input name="password" placeholder='密码' maxlength="16" type='text' autocomplete="off">
	      <div class='validation'>
	        <img alt="" src='/static/img/tick.png'>
	      </div>
	    </div>
	    <div class='login_fields__submit'>
	      	<input type='submit' value='登录'>
            <a href="/uauth/regist/"><input type='button' value='注册'></a>
	    </div>
	  </div>
		</form>
	  <div class='success'>
	  </div>
	  <div class='disclaimer'>
	    <p>欢迎登录后台管理系统</p>
	  </div>
	</div>
	<div class='authent'>
	  <div class="loader" style="height: 44px;width: 44px;margin-left: 28px;">
        <div class="loader-inner ball-clip-rotate-multiple">
            <div></div>
            <div></div>
            <div></div>
        </div>
        </div>
	  <p>认证中...</p>
	</div>
	<div class="OverWindows"></div>
	
    <link href="/static/layui/css/layui.css" rel="stylesheet" type="text/css" />
	
	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src='/static/js/stopExecutionOnTimeout.js?t=1'></script>
    <script type="text/javascript" src="/static/layui/layui.js"></script>
    <script type="text/javascript" src="/static/js/Particleground.js"></script>
    <script type="text/javascript" src="/static/js/Treatment.js"></script>
    <script type="text/javascript" src="/static/js/jquery.mockjax.js"></script>

</body>
</html>

student_and_information/templates/day6_register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="pragma" content="no-cache">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="expires" content="0"> 
	<title>注册界面</title>
    <link href="/static/css/default.css" rel="stylesheet" type="text/css" />
	<!--必要样式-->
    <link href="/static/css/styles.css" rel="stylesheet" type="text/css" />
    <link href="/static/css/demo.css" rel="stylesheet" type="text/css" />
    <link href="/static/css/loaders.css" rel="stylesheet" type="text/css" />

	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>

	<script type="text/javascript">
		function login(){
			err_name = $('#err_name').val()
			err_password = $('#err_password').val()
			if(err_name){
				alert(err_name)
			}else if(err_password){
				alert(err_password)
			}
		}
	</script>

</head>
<body onload="login()">
	<div class='login'>
	  <div class='login_title'>
	    <span>新用户注册</span>
	  </div>
		<input type="hidden" id="err_name" value="{{name}}"/>
		<input type="hidden" id="err_password" value="{{password}}"/>
		<form action="" method="post">
            {% csrf_token %}
	  <div class='login_fields'>
	    <div class='login_fields__user'>
	      <div class='icon'>
	        <img alt="" src='/static/img/user_icon_copy.png'>
	      </div>
	      <input name="name" placeholder='用户名' maxlength="16" type='text' autocomplete="off" value=""/>
	        <div class='validation'>
	          <img alt="" src='/static/img/tick.png'>
	        </div>
	    </div>
	    <div class='login_fields__password'>
	      <div class='icon'>
	        <img alt="" src='/static/img/lock_icon_copy.png'>
	      </div>
	      <input name="password" placeholder='密码' maxlength="16" type='text' autocomplete="off">
	      <div class='validation'>
	        <img alt="" src='/static/img/tick.png'>
	      </div>
	    </div>
	    <div class='login_fields__submit'>
	      	<input type='submit' value='注册'>
			<!-- <input type='button' value='注册'> -->
	    </div>
	  </div>
		</form>
	  <div class='success'>
	  </div>
	  <div class='disclaimer'>
	    <p>欢迎登录后台管理系统</p>
	  </div>
	</div>
	<div class='authent'>
	  <div class="loader" style="height: 44px;width: 44px;margin-left: 28px;">
        <div class="loader-inner ball-clip-rotate-multiple">
            <div></div>
            <div></div>
            <div></div>
        </div>
        </div>
	  <p>认证中...</p>
	</div>
	<div class="OverWindows"></div>
	
    <link href="/static/layui/css/layui.css" rel="stylesheet" type="text/css" />
	
	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src='/static/js/stopExecutionOnTimeout.js?t=1'></script>
    <script type="text/javascript" src="/static/layui/layui.js"></script>
    <script type="text/javascript" src="/static/js/Particleground.js"></script>
    <script type="text/javascript" src="/static/js/Treatment.js"></script>
    <script type="text/javascript" src="/static/js/jquery.mockjax.js"></script>

</body>
</html>

student_and_information/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>显示所有学生信息</title>
</head>
<body>
    {% comment %}
    {% for stuinfo in stuinfos %}
        姓名：{{ stuinfo.s.s_name }}
        电话：{{ stuinfo.s.s_tel }}
        地址：{{ stuinfo.s_addr }}
        头像：
        {% if stuinfo.s_image %}
            <img src="/media/{{ stuinfo.s_image }}" alt="" width="100" height="100">
        {% endif %}
        <br>
    {% endfor %}
    {% endcomment %}
    <a href="{% url 'stu:add' %}">添加学生</a><br>
    <h4>--------------- 分割线 ----------------</h4>
    <button id="displayStu">显示所有学生信息</button>
    <div id="div"><ol id="ol"></ol></div>
    <script src="/static/js/jquery.min.js"></script>
    <script>
        $(function(){
            let urlStr = '/stuapp/student/';
            $('#displayStu').on('click',function () {
                $.ajax({
                    type:"get",
                    url:urlStr,
                    async:true,
                    dataType:'json',
                    error:function () {
                        alert('服务器不堪重负了');
                    },
                    success:function(obj){
                        for(let i = 0; i < obj.length; i++){
                            let content = $('<li>').text("姓名:"+ obj[i].s_name + "---电话:" + obj[i].s_tel +
                                                         "---地址:" + obj[i].s_addr);
                            $('#ol').append(content);
                        }
                    }
                });
            });
        });
    </script>
</body>
</html>

student_and_information/templates/index_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>显示所有学生信息</title>
</head>
<body>
    {% for stu in stus %}
        姓名：{{ stu.s_name }}
        电话：{{ stu.s_tel }}
        地址：{{ stu.stuinfo.s_addr }}
        <br>
    {% endfor %}
    <h4>一共{{ stus.paginator.num_pages }}页/总计{{ stus.paginator.count }}条数据</h4> <!-- 展示分页总数-->
    {% for i in stus.paginator.page_range %}
        <a href="/stuapp/stupage/?page_id={{ i }}">{{ i }}</a>
    {% endfor %}
    <br>
    {% if stus.has_previous %}
        <a href="/stuapp/stupage/?page_id={{ stus.previous_page_number }}">上一页</a>
    {% endif %}
    当前第{{ stus.number }}页
    {% if stus.has_next %}
        <a href="/stuapp/stupage/?page_id={{ stus.next_page_number }}">下一页</a>
    {% endif %}
    <h4>--------------- 分割线 ----------------</h4>
    <a href="{% url 'stu:add' %}">添加学生</a>
</body>
</html>

student_and_information/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页面</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        登录姓名: <input type="text" name="name">
        登录密码: <input type="password" name="password">
        <input type="submit" value="提交">
    </form>
</body>
</html>

student_and_information/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        注册姓名: <input type="text" name="name">
        注册密码: <input type="password" name="password">
        <input type="submit" value="提交">
    </form>
</body>
</html>

student_and_information/templates/requestCount.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>各类请求情况</title>
</head>
<body>
    {% for rc in requestcount %}
        pathname: {{ rc.c_path_name }}
        click_count: {{ rc.c_path_count }}
        <br>
    {% endfor %}
</body>
</html>

student_and_information/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>获取所有学生信息</title>
</head>
<body>
    <button id="showStus">获取所有学生的信息</button>
    <button id="createStus" onclick="add_stus()">创建新学生信息</button>
    <div id="div_stus"></div>
    <div id="div_update_stus"></div>
    <div id="div_add_stus"></div>
    <script src="/static/js/jquery.min.js"></script>
    <script>
        $(function () {
           $('#showStus').on("click",function () {
              $.get('/stuapp/student/',function (ret) {  /*msg：接口返回的信息*/
                  /* alert(msg) */
                  /* alert(msg.length)*/
                  s = '<h5>'+ret.code+'</h5><h5>'+ ret.msg +'</h5><br><table><tr><td>姓名</td><td>id</td><td>地址</td><td>操作</td></tr>';
                  for(let i=0; i<ret.data.length; i++){
                      s += '<tr><td>' + ret.data[i].s_name + '</td>\
                           <td>' + ret.data[i].id + '</td>\
                           <td>'+ ret.data[i].s_addr + '</td><td>\
                           <a href="javascript:;" onclick="update_stu(' + ret.data[i].id + ')">编辑</a>|\
                           <a href="javascript:;" onclick="del_stu(' + ret.data[i].id + ')">删除</a></td></tr>'

                  }
                  s += '</table>';
                  $('#div_stus').html(s)
              },'json');

           });
        });
        function del_stu(i) {
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
            $.ajax({
               url:'/stuapp/student/'+ i + '/',  // 请求的地址
                async:true,
                headers:{'X-CSRFToken':csrf},
               type:'DELETE',  // 操作类型
               dataType:'json',  // 数据类型
               success:function (msg) { //  操作成功后的操作
                   alert("删除成功")
               },
               error:function () { // 操作失败后的操作
                   alert("删除失败")
               }
            });
        }
        function update_stu(i) {
            s = '姓名:<input type="text" id="s_name" name="name"><br>\
            电话:<input type="text" id="s_tel" name="tel"><br>\
            <input type="button" value="提交" onclick="update(' + i + ')">';
            $('#div_update_stus').html(s);
        }
        function update(i) {
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
            s_name = $('#s_name').val();
            s_tel = $('#s_tel').val();
            $.ajax({
               url:'/stuapp/student/'+i+'/',
               type:'PATCH',
               data:{'s_name':s_name,'s_tel':s_tel},  //向后端传递数据，以字典的形式
               dataType:'json',
               headers:{'X-CSRFToken':csrf},
               success:function () {
                   alert('修改成功')
               },
               error:function () {
                   alert('修改失败')
               }
            });
        }
        function add_stus() {
            s = '姓名:<input type="text" name="name" id="s_name">\
            电话:<input type="text" name="tel" id="s_tel">\
            <input type="button" onclick="add()" value="提交">'

            $('#div_add_stus').html(s)
        }

        function add(){
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
            s_name = $('#s_name').val();
            s_tel = $('#s_tel').val();
            $.ajax({
               url:'/stuapp/student/',
               type:'POST',
               data:{'s_name':s_name,'s_tel':s_tel},  //向后端传递数据，以字典的形式
               dataType:'json',
               headers:{'X-CSRFToken':csrf},
               success:function () {
                   alert('添加成功')
               },
               error:function () {
                   alert('添加失败')
               }
            });
        }
    </script>
    {% csrf_token %}
</body>
</html>